import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';



// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>DSAW Photography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="DSAW Photography" message="I capture moments in nature and keep them alive" />
    </>
  )
}
